'use client'
import Footer from '@/components/Footer'
import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Cart from '@/components/Cart'
import { useState } from 'react'

import store from '../redux/store'
import { Provider } from 'react-redux'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const [openCart, setOpenCart] = useState(true)
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>

          <Header />
          {children}
          <Footer />
          </Provider>

          </body>
        </html>
        )
}
