# Generated by Django 4.2.2 on 2023-06-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_color_image_size_remove_product_color_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="ProductImage",
        ),
    ]
