# Generated by Django 4.2.2 on 2023-06-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_rename_image_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="color",
            field=models.CharField(
                default="white", max_length=50, verbose_name="Product Color"
            ),
        ),
    ]
