# Generated by Django 4.2.2 on 2023-06-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_product_slug_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, null=True, verbose_name="Slug"),
        ),
    ]
