# Generated by Django 4.2.2 on 2023-06-27 09:12

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="color",
            field=models.ForeignKey(
                max_length=30,
                on_delete=models.SET(shop.models.get_product_color_text),
                to="shop.color",
                verbose_name="Product Color",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="size",
            field=models.ForeignKey(
                max_length=30,
                on_delete=models.SET(shop.models.get_product_size_text),
                to="shop.size",
                verbose_name="Product Size",
            ),
        ),
    ]
