# Generated by Django 4.2.2 on 2023-06-27 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_alter_orderitem_color_alter_orderitem_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="color",
            field=models.ForeignKey(
                max_length=30,
                on_delete=django.db.models.deletion.RESTRICT,
                to="shop.color",
                verbose_name="Product Color",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="shop.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="size",
            field=models.ForeignKey(
                max_length=30,
                on_delete=django.db.models.deletion.RESTRICT,
                to="shop.size",
                verbose_name="Product Size",
            ),
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fName", models.CharField(max_length=30, verbose_name="First Name")),
                ("lName", models.CharField(max_length=30, verbose_name="Last Name")),
                ("email", models.EmailField(max_length=50, verbose_name="Email")),
                (
                    "number",
                    models.CharField(max_length=30, verbose_name="Phone Number"),
                ),
                (
                    "addNumber",
                    models.CharField(
                        max_length=30, verbose_name="Additional Phone Number"
                    ),
                ),
                ("address", models.CharField(max_length=100, verbose_name="Address")),
                ("totalPrice", models.FloatField(verbose_name="Total Price")),
                (
                    "payment",
                    models.BooleanField(default=False, verbose_name="Payment Done"),
                ),
                (
                    "order_status",
                    models.CharField(
                        default="In Progress",
                        max_length=100,
                        verbose_name="Order Status",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        to="shop.orderitem", verbose_name="Products"
                    ),
                ),
            ],
        ),
    ]
