# Generated by Django 4.2.2 on 2023-06-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_alter_orderitem_color_alter_orderitem_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="trackingId",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Tracking Id"
            ),
        ),
    ]
